---
   summary: |
     Поиск товара по ключевому слову 
  requirement: |
     При вводе ключевого слова происходит поиск соответствующего товара
  prerequisites: |
     - открыта страница сайта 
     - отображен каталог товаров
     - отображено поле поиска
  test-data: |
     - Ключевое слово, напрмер,  Corset
  steps:
     - В поле поиска вводится ключевое слово 
  expected-result: |
     - На странице магазина отображается список товаров, в названии или описании которых содержится ключевое слово
---
   summary: |
     Поиск товара по категории 
  requirement: |
     При поиске товара по категории   происходит поиск товара соответствующей категории
  prerequisites: |
     - открыта страница сайта 
     - отображен каталог товаров
     - отображен список категорий
  test-data: |
     Категория товара 
  steps:
     - Выбираем категорию из списка, например, furniture  
  expected-result: |
     - На странице сайта отображается товар, соответствующий выбранной категории
---
   summary: |
     Поиск товара по категории и ключевому слову одновременно
      requirement: |
   Поиске товара по ключевому слову внутри категории  происходит поиск товара, соответствующего выбранной категории и содержащий в названии или описании ключевое слово
  prerequisites: |
     - открыта страница сайта 
     - Отображен каталог товаров
     - Отображен список категорий
     - Отображено поле поиска
  test-data: |
     Категория товара - напрмер, fragrances
     Ключевое слово - напрмер, one 
  steps:
     - В списке категории выбираем вид товара
     - В поле поиска набираем ключевое слово
  expected-result: |
     - На странице сайта отображается товар, соответствующий выбранной категории  и содержащий в наименовании или описании ключевое слово 
---
   summary: |
     Проверка фильтра товаров по Производителю (Бренду)
  requirement: |
     Пользователь должен иметь возможность фильтровать товары по Производителью (Бренду)
  prerequisites: |
     - открыта страница сайта 
     - отображен каталог товаров
     - отображен список производителей
  test-data: |
     Производитель -  напрмер, Knoll
  steps:
     - Выбирается производитель из списка наименований
     - Обращаем внимание на отобразившиеся товары
  expected-result: |
     На странице  магазина  отображается товар, относящийся к выбранному производителю  
---
   summary: |
     Проверка фильтра товаров по наличию (in stock)
  requirement: |
     Пользователь должен иметь возможность просматривать все товары 
  prerequisites: |
     - открыта страница сайта 
     - отображен каталог товаров
  test-data: |
  В наличии - выбран товар В наличии
  steps:
     - нажать на чекбокс "В наличии"
     - Обращаем внимание на отобразившиеся товары
  expected-result: |
     На странице  магазина  отображаются все товары

---
   summary: |
     Проверка открытии карточки товара
  requirement: |
     Пользователь должен иметь возможность просматривать подробную информацию о товаре
  prerequisites: |
     - no data
  test-data: |
  В наличии - выбран товар В наличии
  steps:
     - выбрать любой товар из каталога
     - нажать на выбранный товар
  expected-result: |
     отображается подробная информация о товаре
---
   summary: |
     Проверка фильтра товаров по цене
  requirement: |
     Пользователь должен иметь возможность фильтровать товары по цене
  prerequisites: |
     - открыта страница сайта 
     - отображен каталог товаров
     - отображены два поля цен в диапазоне от 0 до 6577.499
  test-data: |
     минимальная цена товара - 100
     максимальная цена товара - 150
  steps:
     - выставляется цена в поле минимального диапазона
     - выставляется цена в поле максимального диапазона
  expected-result: |
     На странице  магазина  отображается товар, соответствующий выбранному диапазону цен от 100 до 150
---
   summary: |
     Проверка отображения видов товаров в категориях 
  requirement: |
     В списке категорий должны отображаться все виды товаров, представленные в магазине
  prerequisites: |
     - открыта страница сайта
     - отображен список категорий товаров 
  test-data: |
      No data 
  steps:
     - открыть первую страницу магазина
     - кликнуть на списке категорий
     - открыть последнюю страницу магазина
     - кликнуть на списке категорий
  expected-result: |
     - В списке категорий отображаются все виды товаров
---
   summary: |
     Успешное добавление товара в корзину
  requirement:
     Пользователь должен иметь возможность добавлять товары в корзину
  prerequisites: |
     - открыта страница сайта
     - отображен каталог товаров
  test-data: 
     карточка товара - Knoll Saarinen Executive Conference Chair
     кнопка "Добавить в корзину"
  steps:
     - выбрать товар Knoll Saarinen Executive Conference Chair
     - нажать  на кнопку "Добавить в корзину"
     - открыть корзину
  expected-result:
     выбранный товар добавлен и отображается в корзине
---
   summary: |
     Просмотр содержимого корзины
  requirement:
     Пользователь должен иметь возможность просматривать содержимое корзины
  prerequisites: |
     - открыта страница сайта 
     - в корзине магазина  размещен товар
  test-data: 
     товар - Knoll Saarinen Executive Conference Chair
  steps:
     - выбрать товар Knoll Saarinen Executive Conference Chair
     - добавить выбранный товар в корзину
     - открыть корзину
     - обратить внимание на информацию
  expected-result:
     рядом с товаром отображается информация о количестве, цене единицы и общей стоимости 
---
   summary: |
     Корректировка количества товара в корзине
  requirement: |
     Пользователь должен иметь возможность корректировать количество товара
  prerequisites: |
     - открыта страница сайта 
  test-data: |
     товар - Knoll Saarinen Executive Conference Chair
  steps:
     - открыть каталог товаров
     - выбрать из каталога товар Knoll Saarinen Executive Conference Chair
     - добавить товар в корзину
     - перейти в корзину
     - с помощью функциональных кнопок увеличить или уменьшить количество товара
  expected-result: |
     - С помощью функциональных кнопок корректируется количество товара
---
   summary: |
     Удаление товаров из корзины
  requirement: |
     Пользователь дожен иметь возможность удалить товар из корзины
  prerequisites: |
     - открыта страница сайта 
     - в корзине магазина  размещен товар
  test-data: |
     товар - Knoll Saarinen Executive Conference Chair
  steps:
     - Выбрать товар
     - Положить  товар Knoll Saarinen Executive Conference Chair  в корзину 
     - Перейти в корзину
     - Нажать на кнопку "Удалить"
     - Обновить страницу 
  expected-result: |
     Товар удаляется из корзины
---
   summary: |
     Проверка открытия карточки товара
  requirement: 
     Пользователь должен иметь возможность просматривать подробную информацию о товаре 
  prerequisites: |
     - открыта страница сайта 
     - отображен каталог товаров
  test-data: 
     карточка товара - Powder Canister
  steps:
     - выбираем  товар Powder Canister
     - кликаем на карточку товара
  expected-result:
     Открывается карточка товара с подробным описанием
---
   summary: |
     Обновление страницы магазина
  requirement: |
     При обновлении страницы данные перезагружаются и пользователь остается на открытой странице
  prerequisites: |
     - открыта страница сайта 
  test-data: |
     No data
  steps: 
     - перейти на следующую страницу
     - обновить страницу
     - перейти на последнюю страницу каталога 
     - обновить страницу
  expected-result: |
     - Обновляется открытая страница магазина
---
   summary: |
     Проверка адаптивности сайта для разных разных мобильных устройств
  requirement: |
     При выборе разных мобильных устройств фото товаров, поля поиска, выбора цен, функциональные кнопки отображаются корректно.
  prerequisites: |
     - открыта страница сайта 
  test-data: |
     версии мобильных устройств в DevTools
  steps:
     - Открыть инструмент DevTools, выбрать в меню «Дополнительные инструменты → Инструменты разработчика» и нажать на кнопку «Toggle device toolbar» 
     - Выбрать поочередно разные мобильные устройства  
  expected-result: |
     - При выборе разных мобильных устройств фото товаров, поля поиска, выбора цен, функциональные кнопки отображаются корректно.
---
   summary: |
     Соотвествие закондательству
  requirement: |
     При открытии любой страницы сайта отсутвует информация противоречащая законадательсву.
  prerequisites: |
     - открыта страница сайта 
  test-data: |
     No data
  steps:
     - открыть разные страницы сайта
     - проверить все структурные единицы сайта (шапка, подвал и др.) на отсутствие информации противоречащей законодательству.
  expected-result: |
     - При открытии любой страницы сайта отсутвует информация противоречащая законадательсву.
---
   summary: |
    Ввод чисел в поле Поиск (наименование товара)
  requirement: |
     В поле "Поиск" нельзя ввести цыфры
  prerequisites: |
     - открыта страница сайта 
  test-data: |
      No data
  steps:
      - Выбрать поле  Поиск товара
     - Ввести вручную в поле Поиск (наименование товара) число
  expected-result: |
      - При вводе чисел в поле "Поиск"   нельзя ввести числа
---
   summary: |
     Ввод cпециальных символов в поле Поиск
  requirement: |
     В поле  ввода "Поиск" нельзя ввести специальные символы 
  prerequisites: |
     - открыта страница сайта 
  test-data: |
      No data
  steps:
     - Выбрать поле  Поиск товара 
     - Ввести в поле поиск специальные символы
  expected-result: |
      - При вводе чисел в поле нельзя ввести специальные символы
---
   summary: |
    Поле поиск ограничен вводом символов
  requirement: |
     В поле "Поиск" нельзя ввести больше 1000 символов
  prerequisites: |
     - открыта страница сайта 
  test-data: |
      No data
  steps:
       - Выбрать поле  Поиск товара
     - Ввести вручную в поле Поиск (наименование товара) 1001 символ (букву)
  expected-result: |
      - Поле поиск ограничен вводом 1000 символами 
---
   summary: |
     Ввод отрицательных чисел в поля цен товаров
  requirement: |
     В полях  ввода цен нельзя ввести  отрицательные значения
  prerequisites: |
     - открыта страница сайта 
  test-data: |
      No data
  steps:
     - Выбрать поле  минимальной цены товара 
     - Ввести вручную в поле  отрицательное число
     - Выбрать поле максимальной цены товара 
     - Ввести вручную в поле отрицательное число
  expected-result: |
      - При вводе чисел в поля  цен нельзя ввести отрицательные значения
---
   summary: |
     Ввод cпециальных символов в поля цен товаров
  requirement: |
     В полях  ввода цен нельзя ввести специальные символы 
  prerequisites: |
     - открыта страница сайта 
  test-data: |
      No data
  steps:
     - Выбрать поле  минимальной цены товара 
     - Ввести в поле цены специальные символы
     - Выбрать поле  максимальной цены товара 
     - Ввести в поле специальные символы
  expected-result: |
      - При вводе чисел в поля выбора цен нельзя ввести специальные символы
---
   summary: |
          Ввод значений больше допутимого  в поле максимальная цена товаров
  requirement: |
     В полях  ввода цен нельзя ввести значение больше допустимого
  prerequisites: |
     - открыта страница сайта 
  test-data: |
      No data
  steps:
     - Выбрать поле  максимальной цены товара 
     - Ввести в поле значение 1000000000
     expected-result: |
      - При вводе числа 1000000000 в поле выбора максимальной цены нельзя ввести.
      ---
   summary: |
          при смене языка элементы не смещаются
  requirement: |
     при смене языка  все элементы страницы на своих местах, ничего не смещается
  prerequisites: |
     - открыта страница сайта 
  test-data: |
      No data
  steps:
     - Сменить язык с Англиийского на Руйский 
     expected-result: |
      - при смене языка  все элементы страницы на своих местах, ничего не смещается
      ---
   summary: |
          при смене языка с Английского на русский все слова (кроме брендов) переводятся корректно
  requirement: |
     при смене языка с Английского на русский название и описание товаров переводятся корректно
  prerequisites: |
     - открыта страница сайта 
  test-data: |
      No data
  steps:
     - Сменить язык с Англиийского на Руйский 
     expected-result: |
      - при смене языка с Английского на русский название и описание товаров переводятся корректно
      ---
   summary: |
     Проверка отображения брендов товаров в списке 
  requirement: |
     В списке брендов должны отображаться все бренды, представленные в магазине
  prerequisites: |
     - открыта страница сайта 
     - отображен каталог товаров
     - отображен список брендов
  test-data: |
      No data 
  steps:
     - открыть первую страницу магазина
     - обратить внимание  на  список брендов
     - открыть последнюю страницу магазина
     - обратить внимание на на список брендов
  expected-result: |
     - В списке брендов отображаюся все бренды, представленные в магазине
      ---
      - summary: |
     Проверка отображения  товаров  на разных страницах
  requirement: |
     На страницах отоброжаются товары кооректно и одинаково на всех страницах
  prerequisites: |
     - открыта страница сайта
     - отображен список категорий товаров 
  test-data: |
      No data 
  steps:
     - открыть первую страницу магазина
     - открыть последнюю страницу магазина
  expected-result: |
     - В списке категорий отображаются все виды товаров
      
   ---
      - summary: |
     Проверка оформления заказа
  requirement: |
     Пользователь дожен иметь возможность заказать товар
  prerequisites: |
     - открыта страница сайта
     - отображен список категорий товаров 
  test-data: |
      No data 
  steps:
     - добавить товар в корзину
     - открыть корзину 
     -нажать Checkout
  expected-result: |
     - заказ оформлен
      

