---
- summary: |
     Поиск товара по ключевому слову
  status: fail
---
- summary: |
     Поиск товара по категории
  status: fail
---
- summary: |
     Проверка фильтрации по ключевому слову и категории одновременно
  status: pass
---
- summary: |
     Проверка фильтра товаров по Производителю
  status: pass
---
- summary: |
     Проверка фильтра товаров по наличию
  status: pass
---
- summary: |
     Проверка фильтра товаров по цене
  status: pass
---
---
   - summary: |
     Проверка отображения видов товаров в категориях
 status: fail
---
    - summary: 
     Успешное добавление товара в корзину
      status: pass
---
      - summary:
     Просмотр содержимого корзины
       status: pass
         ---
- summary:
     Корректировка количества товара в корзине
  status: fail
  ---
- summary:
     Удаление товаров из корзины
  status: fail
  ---
  - summary: |
     Проверка открытия карточки товара
       status: pass
  ---
  - summary: |
     Обновление страницы магазина
    status: fail

     - summary: |
     Проверка адаптивности сайта для разных разных мобильных устройств
  status: fail       
---
   - summary: |
     Соотвествие закондательству
    status: pass
---
- summary: |
    Ввод чисел в поле Поиск (наименование товара)
 status: fail
---
 - summary: |
     Ввод cпециальных символов в поле Поиск
 status: fail
---
- summary: |
    Поле поиск ограничен вводом символов
 status: fail
---
- summary: |
     Ввод отрицательных чисел в поля цен товаров
 status: fail
---
      - summary: |
     Ввод cпециальных символов в поля цен товаров
        status: fail
---
      - summary: |
          Ввод значений больше допутимого  в поле максимальная цена товаров
        status: fail
         ---
   summary: |
          При смене языка  все элементы страницы на своих местах, ничего не смещается
            status: pass
              ---
   summary: |
          при смене языка с Английского на русский название и описание товаров переводятся правильно
            status: fail
         ---
   summary: |
     Проверка отображения брендов товаров в списке  
            status: fail
        ---
   summary: |
     Проверка отображения  товаров  на разных страницах
            status: fail
      ---
  - summary: |
     Проверка оформления заказа
          status: fail

       
     
